name: 'AidboxProject'
config-version: 2
version: '0.1'

profile: 'AidboxProject'

models:
  aidbox:
    FHIR:
      +materialized: view
      schema: fhir
  AidboxProject:
    marts:
      +materialized: table
      +unlogged: true
      schema: marts
    views:
      +materialized: table
      +unlogged: true