version: 2
models:
  - name: Patient
    columns: 
    - name: "id"
      tests:
      - aidbox.fhir_uuid
  - name: Observation
    columns: 
    - name: "resource#>>'{ issued }'"
      tests:
      - aidbox.fhir_date
    - name: "resource#>>'{ effective,dateTime }'"
      tests:
      - aidbox.fhir_date
    - name: id
      tests:
      - aidbox.fhir_uuid
    - name: resource#>>'{ subject,id }'
      tests:
      - aidbox.fhir_uuid
    - name: resource#>>'{ encounter,id }'
      tests:
      - aidbox.fhir_uuid
  - name: Encounter 
    columns: 
    - name: "resource#>>'{period,start}'"
      tests:
      - aidbox.fhir_date
    - name: "resource#>>'{period,end}'"
      tests:
      - aidbox.fhir_date
  - name: Procedure
    columns: 
    - name: "resource#>>'{performed,Period,end}'"
      tests:
      - aidbox.fhir_date
    - name: "resource#>>'{performed,Period,start}'"
      tests:
      - aidbox.fhir_date
  - name: Condition
    columns: 
    - name: "resource#>>'{onset,dateTime}'"
      tests:
      - aidbox.fhir_date
    - name: "resource#>>'{abatement,dateTime}'"
      tests:
      - aidbox.fhir_date
    - name: "resource#>>'{recordedDate}'"
      tests:
      - aidbox.fhir_date